<html>
<head>
    <style>
        h1 {
            font-weight: 900;
        }
        h3{
            font-weight: bolder;
            text-decoration: underline;
            margin-top: 40px;
            margin-bottom: 10px;
        }
        h4 {
            text-transform: uppercase;
            font-weight: bold;
            font-size: 16px;
        }
        div{
            font-weight: 600;
        }
    </style>
</head>
<body>

        
    <div class="faq_faqAnswerWrapper_inner container" style="padding: 20px;padding-top: 50px;">
        <h1 style="margin-bottom: 30px;margin-top: 30px;text-align: center;"> TERMS & CONDITIONS</h1>
    
        <h3> GENERAL TERMS OF USE</h3><br>
        <h4>Electronic Record -</h4> <br>
        <div>This document is an electronic record in terms of
            Information Technology Act, 2000 and rules there under as applicable
            and the amended provisions pertaining to electronic records in various
            statutes as amended by the Information Technology Act, 2000. This
            electronic record is generated by a computer system and does not require
            any physical or digital signatures;
            <div><br>
                <h4> APPLICABLE LAWS - </h4><br>
                <div>This document is published in accordance with
                    the provisions of Rule 3 (1) of the Information Technology
                    (Intermediaries guidelines) Rules, 2011 that require publishing the rules
                    and regulations, privacy policy and Terms of Use for access or usage of
                    domain name www.thepetnest.com (“Platform”), including the related
                    mobile site and mobile application (hereinafter referred to as “Platform”)
                    AND all the laws of the Republic of India are and shall be the governing
                    laws for any purpose whatsoever herein;
                </div>
                <br>
                <h4><br>
                    <div> OWNERSHIP OF THE PLATFORM -</div>
                </h4>
                <br>
                <div> The Platform is owned by M/s.
                    Petdos Online Private Limited a company incorporated under the
                    Companies Act, 1956 with its registered office at 55, 2nd Floor, Lane 2, Westend Marg, Saidullajab,
                    Near Saket Metro Station, New Delhi, Delhi, 110030 (hereinafter
                    referred to as "Petdos").
                </div>
                <br>
                <h4>TERMS AND CONDITIONS -</h4><br>
                <div> Your use of the Platform and services
                    and tools are governed by the following terms and conditions ("Terms of
                    Use") as applicable to the Platform including the applicable policies
                    which are incorporated herein by way of reference. It shall be deemed
                    that by accessing, browsing, visiting, or transacting in whatsoever nature /
                    way on the Platform, you unconditionally accept all the Terms of Use and
                    Privacy Policy applicable to the platform specified therein. If you access,
                    browse, visit, or transact in whatsoever nature / way on the Platform, you
                    shall be subject to the policies that are applicable to the Platform for such
                    transaction. By mere use of the Platform, you shall be contracting with
                    Petdos Online Private Limited and these terms and conditions including
                    the policies constitute your binding obligations, with Petdos.
                </div>
                <br>
                <div> For the purpose of these Terms of Use, wherever the context so
                    requires "You" or "User" shall mean any natural or legal person who has
                    agreed to become a buyer on the Platform by providing Registration Data
                    while registering on the Platform as Registered User using the computer
                    systems. Petdos allows the User to surf the Platform or making purchases
                    without registering on the Platform. The term "We", "Us", "Our" shall
                    mean Petdos Online Private Limited.
                </div>
                <br>
                <div> When you use any of the services provided by us through the Platform,
                    including but not limited to, (e.g. Product Reviews, Seller Reviews), you
                    will be subject to the rules, guidelines, policies, terms, and conditions
                    applicable to such service, and they shall be deemed to be incorporated
                    into this Terms of Use and shall be considered as part and parcel of this
                    Terms of Use. We reserve the right, at our sole discretion, to change,
                    modify, add or remove portions of these Terms of Use, at any time
                    without any prior written notice to you. It is your responsibility to review
                    these Terms of Use periodically for updates / changes. Your continued
                    use of the Platform following the posting of changes will mean that you
                    accept and agree to the revisions. As long as you comply with these
                    Terms of Use, we grant you a personal, non-exclusive, non-transferable,
                    limited privilege to enter and use the Platform.
                </div>
                <br>
                <div>Accessing, browsing or otherwise using the site indicates your agreement
                    to all the terms and conditions under these terms of use, so please read the
                    terms of use carefully before proceeding. By impliedly or expressly
                    accepting these Terms of Use, you also accept and agree to be bound by
                    Petdos Policies (including but not limited to Privacy Policy available at
                    the platform) as amended from time to time.
                </div>
                <br>
                <h3> MEMBERSHIP AND REGISTRATION OF ACCOUNTS</h3><br>
                <h4> MEMBERSHIP ELIGIBILITY - </h4><br>
                <div>Use of the Platform is available only to
                    persons who can form legally binding contracts under Indian Contract
                    Act, 1872. Persons who are "incompetent to contract" within the meaning
                    of the Indian Contract Act, 1872 including minors, un-discharged
                    insolvents etc. are not eligible to use the Platform. If you are a minor i.e.
                    under the age of 18 years, you shall not register as a user of the Petdos
                    Platform and shall not transact on or use the Platform. As a minor if you
                    wish to use or transact on Platform, such use or transaction may be made
                    by your legal guardian or parents on the Platform. Petdos reserves the
                    right to terminate your membership and / or refuse to provide you with
                    access to the Platform if it is brought to Petdos's notice or if it is
                    discovered that you are under the age of 18 years. It is also put to
                    disclaimer / caveat / intimation / notice that all legal - requirements,
                    sanctions, restrictions, licenses, authorizations, authorities, attornments,
                    representations, notifications, classifications, mandates of law including
                    and excluding the law for the time being in force or otherwise; or
                    otherwise ejusdem genris qua the user shall be his / her own, sole and
                    personal responsibility and that neither the platform nor Petdos Online
                    Private Limited shall be responsible in any manner under any
                    circumstance or whatsoever nature for any liability whether civil,
                    criminal, vicarious, personal, professional and commercial under
                    mandates of law including and excluding the law for the time being in
                    force or otherwise; or otherwise.
                </div>
                <br>
                <h4> YOUR ACCOUNT AND REGISTRATION OBLIGATIONS - </h4><br>
                <div>If you use
                    the Platform, you shall be responsible for maintaining the confidentiality
                    of your Display Name and Password and you shall be responsible for all
                    activities that occur under your Display Name and Password. You agree
                    that if you provide any information that is untrue, inaccurate, not current
                    or incomplete or we have reasonable grounds to suspect that such
                    information is untrue, inaccurate, not current or incomplete, or not in
                    accordance with this Terms of Use, we shall have the right to indefinitely
                    suspend or terminate or block access of your membership on the Platform
                    and refuse to provide you with access to the Platform.
                </div>
                <br>
                <div> Your mobile phone number and/or e-mail address is treated as your
                    primary identifier on the Platform. It is your responsibility to ensure that
                    your mobile / cellular phone number and your email address is always up
                    to date on the Platform at all times. you agree to notify us promptly if
                    your mobile phone number or e-mail address changes by updating the
                    same on the Platform through a onetime password verification.
                </div>
                <br>
                <div> You agree that Petdos shall not be liable or responsible for the activities
                    or consequences of use or misuse of any information that occurs under
                    your display name in cases where you have failed to update your revised
                    mobile / cellular phone number and/or e-mail address on the Platform.
                </div>
                <br>
                <h4>COMMUNICATIONS -</h4><br>
                <div> When you use the Platform or send emails or
                    other data, information or communication to us, you agree and understand
                    that you are communicating with us through electronic records and you
                    consent to receive communications via electronic records from us
                    periodically and as and when required. We may communicate with you
                    by email or by such other mode of communication, electronic or
                    otherwise. That communication on chat messengers or IVR – messengers
                    based on social media platforms / channels or otherwise shall also stand
                    binding upon the users, to be a medium of communication.
                </div>
                <br>
                <h4>CHARGES - </h4><br>
                <div>Registration on the Platform is free for buyers. Petdos does
                    not charge any fee for browsing and buying on the Platform. Petdos
                    reserves the right to change its Fee Policy from time to time. In particular,
                    Petdos may at its sole discretion introduce new services and modify some
                    or all of the existing services offered on the Platform. That the platform
                    shall levy a charge and / or fee and / or commission and / or fine and / or
                    security from the sellers, service providers or others who list products on
                    the platform; the sellers, service providers or others who list products on
                    the platform unconditionally accept the liability to pay such charge and /
                    or fee and / or commission and / or fine and / or security. In such an
                    event Petdos reserves the right to introduce fees for the new services
                    offered or amend/introduce fees for existing services, as the case may be.
                    Changes to the Fee Policy shall be posted on the Platform and such
                    changes shall automatically become effective immediately after they are
                    posted on the Platform. Unless otherwise stated, all fees shall be quoted
                    in Indian Rupees. You shall be solely responsible for compliance of all
                    applicable laws including those in India for making payments to Petdos
                    Online Private Limited.
                </div>
                <br>
                <div>
                    <p>To enhance the sustainability of ThePetNest Premium membership program for both ThePetNest and our valued
                        service professionals, we are implementing a fair usage policy for ThePetNest Premium memberships, effective
                        from 2nd October 2023.</p>
    
                    <ul>
                        <li>
                            <b>Discount Cap:</b> ThePetNest memberships are designed for individual use. To maintain this principle, we
                            are capping the total discount limit for a ThePetNest Premium member at 10% of the total service order
                            value.
                        </li>
                        <li>
                            <b>Per Transaction Limit:</b> In addition, we will introduce a per transaction limit for ThePetNest Premium.
                            Subscribers can enjoy a maximum discount of 10% or Rs 500, whichever is lower, on the order value in a
                            single booking.
                        </li>
                        <li>
                            <b>Non-refundable and Non-transferable:</b> Please note that ThePetNest Premium membership plans are
                            non-refundable and non-transferrable.
                        </li>
                    </ul>
    
                    <p>
                        We have implemented these changes to ensure fair usage and prevent any potential misuse of the subscription
                        program, enabling us to continue providing exceptional service to all our members.
                        At ThePetNest, customer satisfaction is our top priority. If you have any questions about these changes, feel
                        free to contact us at <a href="/cdn-cgi/l/email-protection" class="_cf_email_" data-cfemail="780b0d0808170a0c380c101d081d0c161d0b0c561b1715">[email&#160;protected]</a>. We will promptly respond to your queries and address any
                        concerns you may have.
                    </p>
                    <br>
                </div>
                <h3> USE OF THE PLATFORM</h3><br>
                <div> You agree, undertake and confirm that your use of Platform shall be
                    strictly governed by the following binding principles:<br>
                    <div> You shall not host, display, upload, modify, publish, transmit, update
                        or share any information which:<br><br>
                        <span> Belongs to another person and to which you do not have any right to;</span><br><br>
                        <span> Is grossly harmful, harassing, blasphemous, defamatory, obscene,
    pornographic, pedophilic, libelous, invasive of another's privacy,
    hateful, or racially, ethnically objectionable, disparaging, relating or
    encouraging money laundering or gambling, or otherwise unlawful in
    any manner whatever; or unlawfully threatening or unlawfully
    harassing including but not limited to "indecent representation of
    women" within the meaning of the Indecent Representation of Women
    (Prohibition) Act, 1986;</span><br><br>
                        <span> Is misleading in any way;</span><br><br>
                        <span> Is patently offensive to the online community, such as sexually
    explicit content, or content that promotes obscenity, pedophilia,
    racism, bigotry, hatred or physical harm of any kind against any group
    or individual;</span><br><br>
                        <span> Harasses or advocates harassment of another person;</span><br><br>
                        <span>Involves the transmission of "junk mail", "chain letters", or unsolicited
    mass mailing or "spamming";</span><br><br>
                        <span> Promotes illegal activities or conduct that is abusive, threatening,
    obscene, defamatory or libelous upon or violates any third party's
    rights [including, but not limited to, intellectual property rights, rights
    of privacy (including without limitation unauthorized disclosure of a
    person's name, email address, physical address or phone number) or
    rights of publicity];</span><br><br>
                        <span>Promotes an illegal or unauthorized copy of another person's</span><br><br>
                        <span> copyrighted work (see "Copyright complaint" below for instructions
    on how to lodge a complaint about uploaded copyrighted material),
    such as providing pirated computer programs or links to them,
    providing information to circumvent manufacture-installed copyprotect devices, or providing pirated music or links to pirated music
    files;</span><br><br>
                        <span> Contains restricted or password-only access pages, or hidden pages or
    images (those not linked to or from another accessible page);</span><br><br>
                        <span> Provides material that exploits people in a sexual, violent or otherwise
    inappropriate manner or solicits personal information from anyone;</span><br><br>
                        <span> Provides instructional information about illegal activities such as
    making or buying illegal weapons, violating someone's privacy, or
    providing or creating computer viruses;</span><br><br>
                        <span>Contains video, photographs, or images of another person (with a
    minor or an adult).</span><br><br>
                        <span>Tries to gain unauthorized access or exceeds the scope of authorized
    access to the Platform or to profiles, blogs, communities, account
    information, bulletins, friend request, or other areas of the Platform or
    solicits passwords or personal identifying information for commercial
    or unlawful purposes from other users;</span><br><br>
                        <span> Engages in commercial activities and/or sales without our prior
    written consent such as contests, sweepstakes, barter, advertising and
    pyramid schemes, or the buying or selling of "virtual" products related
    to the Platform. Throughout this Terms of Use, Petdos's prior written
    consent means a communication coming from Petdos's Legal
    Department, specifically in response to your request, and specifically
    addressing the activity or conduct for which you seek authorization;</span><br><br>
                        <span> Solicits gambling or engages in any gambling activity which we, in
    our sole discretion, believes is or could be construed as being illegal;</span><br><br>
                        <span>Interferes with another USER's use and enjoyment of the Platform or
    any other individual's user and enjoyment of similar services;</span><br><br>
                        <span> Refers to any Platform or URL that, in our sole discretion, contains
    material that is inappropriate for the Platform or any other Platform,
    contains content that would be prohibited or violates the letter or spirit
    of these Terms of Use.</span><br><br>
                        <span> Harm minors in any way;</span><br><br>
                        <span>Infringes any patent, trademark, copyright or other proprietary rights
    or third party's trade secrets or rights of publicity or privacy or shall
    not be fraudulent or involve the sale of counterfeit or stolen products;</span><br><br>
                        <span> Violates any law for the time being in force;</span><br><br>
                        <span>Deceives or misleads the addressee / users about the origin of such
    messages or communicates any information which is grossly offensive
    or menacing in nature;</span><br><br>
                        <span> Impersonate another person;</span><br><br>
                        <span> Contains software viruses or any other computer code, files or
    programs designed to interrupt, destroy or limit the functionality of
    any computer resource; or contains any trojan horses, worms, time
    bombs, cancelbots, Easter eggs or other computer programming
    routines that may damage, detrimentally interfere with, diminish value
    of, surreptitiously intercept or expropriate any system, data or personal
    information;</span><br><br>
                        <span>Threatens the unity, integrity, defence, security or sovereignty of
    India, friendly relations with foreign states, or public order or causes
    incitement to the commission of any cognizable offence or prevents
    investigation of any offence or is insulting any other nation.</span><br><br>
                        <span>Shall not be false, inaccurate or misleading;</span><br><br>
                        <span> Shall not, directly or indirectly, offer, attempt to offer, trade or attempt
    to trade in any item, the dealing of which is prohibited or restricted in
    any manner under the provisions of any applicable law, rule,
    regulation or guideline for the time being in force.</span><br>
                        <span>Shall not create liability for us or cause us to lose (in whole or in part)
    the services of our internet service provider ("ISPs") or other
    suppliers;</span><br></div>
                </div>
                <div> You shall not use any "deep-link", "page-scrape", "robot", "spider" or
                    other automatic device, program, algorithm or methodology, or any
                    similar or equivalent manual process, to access, acquire, copy or
                    monitor any portion of the Platform or any content, or in any way
                    reproduce or circumvent the navigational structure or presentation of
                    the Platform or any Content, to obtain or attempt to obtain any
                    materials, documents or information through any means not purposely
                    made available through the Platform. We reserve our right to bar any
                    such activity.
                </div>
                <br>
                <div> In general, you can browse the website without telling us who you are
                    or revealing any personal information about yourself. Once you give
                    us your personal information, you are not anonymous to us. Where
                    possible, we indicate which fields are required and which fields are
                    optional. You always have the option to not provide information by
                    choosing not to use a particular service or feature on the website. We
                    may automatically track certain information about you based upon
                    your behavior on our website. We use this information to do internal
                    research on our users' demographics, interests, and behavior to better
                    understand, protect and serve our users. This information is compiled
                    and analyzed on an aggregated basis. This information may include
                    the URL that you just came from (whether this URL is on our Website
                    or not), which URL you next go to (whether this URL is on our
                    Website or not), your computer browser information, and your IP
                    address.
                </div>
                <br>
                <div> We use data collection devices such as "cookies" on certain pages of
                    the Website to help analyze our web page flow, measure promotional
                    effectiveness, and promote trust and safety. "Cookies" are small files
                    placed on your hard drive that assist us in providing our services. We
                    offer certain features that are only available through the use of a
                    "cookie". We also use cookies to allow you to enter your password
                    less frequently during a session. Cookies can also help us provide
                    information that is targeted to your interests. Most cookies are
                    "session cookies," meaning that they are automatically deleted from
                    your hard drive at the end of a session. You are always free to decline
                    our cookies if your browser permits, although in that case you may not
                    be able to use certain features on the Website and you may be required
                    to re-enter your password more frequently during a session.
                    Additionally, you may encounter "cookies" or other similar devices on
                    certain pages of the Website that are placed by third parties. We do not
                    control the use of cookies by third parties. If you choose to buy on the
                    Website, we collect information about your buying behaviour,
                    preferences, and other such information that you choose to provide. If
                    you transact with us, we collect some additional information, such as a
                    billing address, a credit / debit card number and a credit / debit card
                    expiration date and/ or other payment instrument details and tracking
                    information from cheques or money orders. If you choose to post
                    messages on our message boards, chat rooms or other message areas
                    or leave feedback or if you use voice commands to shop on the
                    Website, we will collect that information you provide to us. We retain
                    this information as necessary to resolve disputes, provide customer
                    support and troubleshoot problems as permitted by law. If you send us
                    personal correspondence, such as emails or letters, or if other users or
                    third parties send us correspondence about your activities or postings
                    on the Website, we may collect such information into a file specific to
                    you. We collect personally identifiable information (email address,
                    name, phone number, credit card / debit card / other payment
                    instrument details, etc.) from you when you set up a free account with
                    us. While you can browse some sections of our Website without being
                    a registered member, certain activities (such as placing an order) do
                    require registration. We do use your contact information to send you
                    offers based on your previous orders and your interests.
                </div>
                <br>
                <div>You shall not attempt to gain unauthorized access to any portion or
                    feature of the Platform, or any other systems or networks connected to
                    the Platform or to any server, computer, network, or to any of the
                    services offered on or through the Platform, by hacking, password
                    "mining" or any other illegitimate means.
                </div>
                <br>
                <div> You shall not probe, scan or test the vulnerability of the Platform or
                    any network connected to the Platform nor breach the security or
                    authentication measures on the Platform, or any network connected to
                    the Platform. you may not reverse look-up, trace or seek to trace any
                    information on any other User of or visitor to Platform, or any other
                    customer, including any account on the Platform not owned by you, to
                    its source, or exploit the Platform or any service or information made
                    available or offered by or through the Platform, in any way where the
                    purpose is to reveal any information, including but not limited to
                    personal identification or information, other than your own
                    information, as provided for by the Platform.
                </div>
                <br>
                <div> You shall not make any negative, denigrating or defamatory
                    statement(s) or comment(s) about Us or the brand name or domain
                    name used by Us including the terms Petdos, www.thepetnest.com,
                    or otherwise engage in any conduct or action that might tarnish the
                    image or reputation, of Petdos or sellers on platform or otherwise
                    tarnish or dilute any Petdos's trade or service marks, trade name and/or
                    goodwill associated with such trade or service marks, trade name as
                    may be owned or used by us. you agree that you will not take any
                    action that imposes an unreasonable or disproportionately large load
                    on the infrastructure of the Platform or Petdos's systems or networks,
                    or any systems or networks connected to Petdos.
                </div>
                <br>
                <div>You agree not to use any device, software or routine to interfere or
                    attempt to interfere with the proper working of the Platform or any
                    transaction being conducted on the Platform, or with any other
                    person's use of the Platform.
                </div>
                <br>
                <div>You may not forge headers or otherwise manipulate identifiers in
                    order to disguise the origin of any message or transmittal you send to
                    Us on or through the Platform or any service offered on or through the
                    Platform. you may not pretend that you are, or that you represent,
                    someone else, or impersonate any other individual or entity.
                </div>
                <br>
                <div> You may not use the Platform or any content for any purpose that is
                    unlawful or prohibited by these Terms of Use, or to solicit the
                    performance of any illegal activity or other activity which infringes
                    the rights of Petdos and / or others.
                </div>
                <br>
                <div>You shall at all times ensure full compliance with the applicable
                    provisions of the Information Technology Act, 2000 and rules
                    thereunder as applicable and as amended from time to time and also
                    all applicable Domestic laws, rules and regulations (including the
                    provisions of any applicable Exchange Control Laws or Regulations in
                    Force) and International Laws, Foreign Exchange Laws, Statutes,
                    Ordinances and Regulations (including, but not limited to Sales
                    Tax/VAT, Income Tax, Octroi, Service Tax, Central Excise, Custom
                    Duty, GST, Local Levies) regarding your use of Our service and your
                    listing, purchase, solicitation of offers to purchase, and sale of
                    products or services. you shall not engage in any transaction in an item
                    or service, which is prohibited by the provisions of any applicable law
                    including exchange control laws or regulations for the time being in
                    force.
                </div>
                <br>
                <div>Solely to enable us to use the information you supply us with, so that
                    we are not violating any rights you might have in your Information,
                    you agree to grant us a non-exclusive, worldwide, perpetual,
                    irrevocable, royalty-free, sub-licensable (through multiple tiers) right
                    to exercise the copyright, publicity, database rights or any other rights
                    you have in your Information, in any media now known or not
                    currently known, with respect to your Information. We will only use
                    your information in accordance with the Terms of Use and Privacy
                    Policy applicable to use of the Platform.
                </div>
                <br>
                <div> From time to time, you shall be responsible for providing information
                    relating to the products or services proposed to be sold by you. In this
                    connection, you undertake that all such information shall be accurate
                    in all respects. You shall not exaggerate or over emphasize the
                    attributes of such products or services so as to mislead other users in
                    any manner.
                </div>
                <br>
                <div>You shall not engage in advertising to, or solicitation of, other users of
                    the Platform to buy or sell any products or services, including, but not
                    limited to, products or services related to that being displayed on the
                    Platform or related to us. you may not transmit any chain letters or
                    unsolicited commercial or junk email to other users via the Platform.
                    It shall be a violation of these Terms of Use to use any information
                    obtained from the Platform in order to harass, abuse, or harm another
                    person, or in order to contact, advertise to, solicit, or sell to another
                    person other than us without our prior explicit consent. In order to
                    protect our users from such advertising or solicitation, we reserve the
                    right to restrict the number of messages or emails which a user may
                    send to other users in any 24-hour period which we deem appropriate
                    in its sole discretion. You understand that we have the right at all
                    times to disclose any information (including the identity of the persons
                    providing information or materials on the Platform) as necessary to
                    satisfy any law, regulation or valid governmental request. This may
                    include, without limitation, disclosure of the information in
                    connection with investigation of alleged illegal activity or solicitation
                    of illegal activity or in response to a lawful court order or subpoena. In
                    addition, We can (and you hereby expressly authorize us to) disclose
                    any information about you to law enforcement or other government
                    officials, as we, in our sole discretion, believe necessary or appropriate
                    in connection with the investigation and/or resolution of possible
                    crimes, especially those that may involve personal injury.
                </div>
                <br>
                <div>We reserve the right, but have no obligation, to monitor the materials
                    posted on the Platform. Petdos shall have the right to remove or edit
                    any content that in its sole discretion violates, or is alleged to violate,
                    any applicable law or either the spirit or letter of these Terms of Use.
                    Notwithstanding this right, you remain solely responsible for the
                    content of the materials you post on the platform and in your private
                    messages. Please be advised that such content posted does not
                    necessarily reflect Petdos views. In no event shall Petdos assume or
                    have any responsibility or liability for any content posted or for any
                    claims, damages or losses resulting from use of content and/or
                    appearance of content on the Platform. You hereby represent and
                    warrant that you have all necessary rights in and to all content which
                    you provide and all information it contains and that such content shall
                    not infringe any proprietary or other rights of third parties or contain
                    any libelous, tortious, or otherwise unlawful information.
                </div>
                <br>
                <div> Your correspondence or business dealings with, or participation in
                    promotions of, advertisers found on or through the Platform, including
                    payment and delivery of related products or services, and any other
                    terms, conditions, warranties or representations associated with such
                    dealings, are solely between you and such advertiser. We shall not be
                    responsible or liable for any loss or damage of any sort incurred as the
                    result of any such dealings or as the result of the presence of such
                    advertisers on the Platform.
                </div>
                <br>
                <div> It is possible that other users (including unauthorized users or
                    "hackers") may post or transmit offensive or obscene materials on the
                    Platform and that you may be involuntarily exposed to such offensive
                    and obscene materials. It also is possible for others to obtain personal
                    information about you due to your use of the Platform, and that the
                    recipient may use such information to harass or injure you. We do not
                    approve of such unauthorized uses, but by using the Platform you
                    acknowledge and agree that we are not responsible for the use of any
                    personal information that you publicly disclose or share with others on
                    the Platform. Please carefully select the type of information that you
                    publicly disclose or share with others on the Platform.
                </div>
                <br>
                <div>Petdos shall have all the rights to take necessary action and claim
                    damages that may occur due to your involvement/participation in any
                    way on your own or through group/s of people, intentionally or
                    unintentionally in DoS/DDoS (Distributed Denial of Services).
                </div>
                <br>
                <div>If you choose to browse or transact on the Platform using the voice
                    command-based shopping feature, you acknowledge that Petdos
                    and/or its affiliates will collect, store and use your voice inputs on this
                    feature to customize your experience and provide additional
                    functionality as well as to improve Petdos’s and/or its affiliates’
                    products and services. Petdos’s and/or its affiliates’ use of your voice
                    data will be in accordance with the Petdos Privacy Policy. You accept
                    that your use of this feature is restricted to the territory of the Republic
                    of India. This feature may not be accessible on certain devices and
                    requires an internet connection. Petdos reserves the right to change,
                    enhance, suspend, or discontinue this feature, or any part of it, at any
                    time without notice to you. Your continued use of this feature
                    constitutes your acceptance of the terms related to this feature.
                </div>
                <br>
                <div>You acknowledge and agree that Hindi translation feature is made
                    available on the Website on a reasonable effort basis for convenience
                    only, without any representation or warranties by Petdos, express or
                    implied, including it being error free, its accuracy, completeness or
                    reliability. Petdos expressly disclaims any liability of any nature
                    whatsoever arising from or related to the said Hindi translation
                    feature. Some features and sections on the Website may not be
                    translated in Hindi language, and the English version of the same will
                    be the definitive version. In the event of any conflict or inconsistency
                    between the translated terms and the English version available on the
                    Website, the English version on the Website shall prevail. This feature
                    may not be accessible on certain devices. Petdos reserves the right to
                    change, enhance, suspend, or discontinue this feature, or any part of it,
                    at any time without notice to you.
                </div>
                <br>
                <h3> CONTENTS POSTED ON PLATFORM</h3><br>
                <div>All text, graphics, user interfaces, visual interfaces, photographs,
                    trademarks, logos, sounds, music and artwork (collectively,
                    "Content"), is a third party user generated content and Petdos has no
                    control over such third party user generated content as Petdos is
                    merely an intermediary for the purposes of this Terms of Use.
                </div>
                <br>
                <div>Except as expressly provided in these Terms of Use, no part of the
                    Platform and no Content may be copied, reproduced, republished,
                    uploaded, posted, publicly displayed, encoded, translated, transmitted
                    or distributed in any way (including "mirroring") to any other
                    computer, server, Platform or other medium for publication or
                    distribution or for any commercial enterprise, without Petdos's express
                    prior written consent.
                </div>
                <br>
                <div> You may use information on the products and services purposely
                    made available on the Platform for downloading, provided that you (1)
                    do not remove any proprietary notice language in all copies of such
                    documents, (2) use such information only for your personal, noncommercial informational purpose and do not copy
                    or post such
                    information on any networked computer or broadcast it in any media,
                    (3) make no modifications to any such information, and (4) do not
                    make any additional representations or warranties relating to such
                    documents.
                </div>
                <br>
                <div>You shall be responsible for any notes, messages, emails, billboard
                    postings, photos, drawings, profiles, opinions, ideas, images, videos,
                    audio files or other materials or information posted or transmitted to
                    the Platform (collectively, "Content"). Such content will become our
                    property and you grant us the worldwide, perpetual and transferable
                    rights in such Content. We shall be entitled to, consistent with our
                    Privacy Policy as adopted in accordance with applicable law, use the
                    Content or any of its elements for any type of use forever, including
                    but not limited to promotional and advertising purposes and in any
                    media whether now known or hereafter devised, including the creation
                    of derivative works that may include the Content you provide. You
                    agree that any Content you post may be used by us, consistent with
                    our Privacy Policy and Rules of Conduct on Site as mentioned herein,
                    and you are not entitled to any payment or other compensation for
                    such use.
                </div>
                <br>
                <h3>PRIVACY</h3><br>
                <div>We view protection of your privacy as a very important principle. We
                    understand clearly that you and your Personal Information is one of
                    our most important assets. We store and process your Information
                    including any sensitive financial information collected (as defined
                    under the Information Technology Act, 2000), if any, on computers
                    that may be protected by physical as well as reasonable technological
                    security measures and procedures in accordance with Information
                    Technology Act 2000 and Rules there under. Our current Privacy
                    Policy is available at Privacy. If you object to your Information being
                    transferred or used in this way, please do not use Platform.
                </div>
                <br>
                <div>We may share personal information with our other corporate entities
                    and affiliates. These entities and affiliates may market to you as a
                    result of such sharing unless you explicitly opt-out.
                </div>
                <br>
                <div>We may disclose personal information to third parties. This disclosure
                    may be required for us to provide you access to our Services, to
                    comply with our legal obligations, to enforce our User Agreement, to
                    facilitate our marketing and advertising activities, or to prevent, detect,
                    mitigate, and investigate fraudulent or illegal activities related to our
                    Services. We do not disclose your personal information to third parties
                    for their marketing and advertising purposes without your explicit
                    consent.
                </div>
                <br>
                <div>We may disclose personal information if required to do so by law or in
                    the good faith belief that such disclosure is reasonably necessary to
                    respond to subpoenas, court orders, or other legal process. We may
                    disclose personal information to law enforcement offices, third party
                    rights owners, or others in the good faith belief that such disclosure is
                    reasonably necessary to: enforce our Terms or Privacy Policy; respond
                    to claims that an advertisement, posting or other content violates the
                    rights of a third party; or protect the rights, property or personal safety
                    of our users or the general public.
                </div>
                <br>
                <div> We and our affiliates will share / sell some or all of your personal
                    information with another business entity should we (or our assets)
                    plan to merge with, or be acquired by that business entity, or reorganization, amalgamation, restructuring of
                    business. Should such a
                    transaction occur that other business entity (or the new combined
                    entity) will be required to follow this privacy policy with respect to
                    your personal information.
                </div>
                <br>
                <h3>DISCLAIMER OF WARRANTIES AND LIABILITY</h3><br>
                <div>This Platform, all the materials and products (including but not limited
                    to software) and services, included on or otherwise made available to
                    you through this site are provided on "as is" and "as available" basis
                    without any representation or warranties, express or implied except
                    otherwise specified in writing. Without prejudice to the forgoing
                    paragraph, Petdos does not warrant that:<br><br>
                    <span>This Platform will be constantly available, or available at all; or</span><br><br>
                    <span>The information on this Platform is complete, true, accurate or non misleading in all reasonable measures.</span><br><br>
                    <span> Petdos will not be liable to you in any way or in relation to the
    Contents of, or use of, or otherwise in connection with, the Platform.
    Petdos does not warrant that this site; information, Content, materials,
    product (including software) or services included on or otherwise
    made available to you through the Platform; their servers; or
    electronic communication sent from us are free of viruses or other
    harmful components.</span><br><br>
                    <span> Nothing on Platform constitutes, or is meant to constitute, advice of
    any kind. All the Products sold on Platform are governed by different
    state laws and if Seller is unable to deliver such Products due to
    implications of different state laws, Seller will return or will give
    credit for the amount (if any) received in advance by Seller from the
    sale of such Product that could not be delivered to you.</span><br><br>
                    <span> You will be required to enter a valid phone number while placing an
    order on the Platform. By registering your phone number with us, you
    consent to be contacted by us via phone calls, SMS notifications,
    mobile applications and/or any other electronic mode of
    communication in case of any order or shipment or delivery related
    updates. We will not use your personal information to initiate any
    promotional phone calls or SMS.</span><br><br>
                    <span><h4>DISCLAIMER:</h4><br> Pricing on any product(s) as is reflected on the
    Platform may due to some technical issue, typographical error or 
    product information published by seller may be incorrectly reflected
    and in such an event seller may cancel such your order(s).</span>
                </div>
                <br>
                <h3>LIABILITY AND RESPONSIBILITY OF TRANSACTION</h3><br>
                <h4> PLATFORM FOR TRANSACTION AND COMMUNICATION - </h4><br>
                <div>This Platform is a platform that users utilize to meet and interact with
                    one another for their transactions. Petdos is not and cannot be a party
                    to or control in any manner any transaction between the Platform's
                    Users. Henceforward:<br><br>
                    <div>All commercial/contractual terms are offered by and agreed to
                        between Buyers and Sellers alone. The commercial/contractual terms
                        include without limitation price, shipping costs, payment methods,
                        payment terms, date, period and mode of delivery, warranties related
                        to products and services and after sales services related to products
                        and services. Petdos does not have any control or does not determine
                        or advise or in any way involve itself in the offering or acceptance of
                        such commercial/contractual terms between the Buyers and Sellers.
                        All discounts and offers (including exchange offers) are by the Seller /
                        Brand and not by Petdos.
                    </div>
                    <br>
                    <div>Placement of order by a Buyer with Seller on the Platform is an offer
                        to buy the product(s) in the order by the Buyer to the Seller and it shall
                        not be construed as Seller's acceptance of Buyer's offer to buy the
                        product(s) ordered. The Seller retains the right to cancel any such
                        order placed by the Buyer, at its sole discretion and the Buyer shall be
                        intimated of the same by way of an email/SMS. Any transaction price
                        paid by Buyer in case of such cancellation by Seller, shall be refunded
                        to the Buyer. Further, the Seller may cancel an order wherein the
                        quantities exceed the typical individual consumption. This applies
                        both to the number of products ordered within a single order and the
                        placing of several orders for the same product where the individual
                        orders comprise a quantity that exceeds the typical individual
                        consumption. What comprises a typical individual's consumption
                        quantity limit shall be based on various factors and at the sole
                        discretion of the Seller and may vary from individual to individual.
                    </div>
                    <br>
                    <div> Petdos does not make any representation or warranty as to specifics
                        (such as quality, value, salability, etc) of the products or services
                        proposed to be sold or offered to be sold or purchased on the Platform.
                        Petdos does not implicitly or explicitly support or endorse the sale or
                        purchase of any products or services on the Platform. Petdos accepts
                        no liability for any errors or omissions, whether on behalf of itself or
                        third parties.
                    </div>
                    <br>
                    <div>Petdos is not responsible for any non-performance or breach of any
                        contract entered into between Buyers and Sellers. Petdos cannot and
                        does not guarantee that the concerned Buyers and/or Sellers will
                        perform any transaction concluded on the Platform. Petdos shall not
                        and is not required to mediate or resolve any dispute or disagreement
                        between Buyers and Sellers.
                    </div>
                    <br>
                    <div> Petdos does not make any representation or warranty as to the itemspecifics (such as legal title,
                        creditworthiness, identity, etc) of any of
                        its users. You are advised to independently verify the bona fides of
                        any particular user that you choose to deal with on the Platform and
                        use your best judgment in that behalf.
                    </div>
                    <br>
                    <div>Petdos does not at any point of time during any transaction between
                        Buyer and Seller on the Platform come into or take possession of any
                        of the products or services offered by Seller nor does it at any point
                        gain title to or have any rights or claims over the products or services
                        offered by Seller to Buyer.
                    </div>
                    <br>
                    <div>At no time shall Petdos hold any right, title or interest over the
                        products nor shall Petdos have any obligations or liabilities in respect
                        of such contract entered into between Buyers and Sellers. Petdos is not
                        responsible for unsatisfactory or delayed performance of services or
                        damages or delays as a result of products which are out of stock,
                        unavailable or back ordered.
                    </div>
                    <br>
                    <div>The Platform is only a platform that can be utilized by users to reach a
                        larger base to buy and sell products or services. Petdos is only
                        providing a platform for communication and it is agreed that the
                        contract for sale of any of the products or services shall be a strictly
                        bipartite contract between the Seller and the Buyer.
                    </div>
                    <br>
                    <div>At no time shall Petdos hold any right, title or interest over the
                        products nor shall Petdos have any obligations or liabilities in respect
                        of such contract.
                    </div>
                    <br>
                    <div> Petdos is not responsible for unsatisfactory or delayed performance of
                        services or damages or delays as a result of products which are out of
                        stock, unavailable or back ordered.
                    </div>
                    <br>
                    <div> You shall independently agree upon the manner and terms and
                        conditions of delivery, payment, insurance etc. with the seller(s) that
                        you transact with.
                    </div>
                    <br>
                    <div>You release and indemnify Petdos and/or any of its officers and
                        representatives from any cost, damage, liability or other consequence
                        of any of the actions of the users of the Platform and specifically
                        waive any claims that you may have in this behalf under any
                        applicable law. Notwithstanding its reasonable efforts in that behalf,
                        Petdos cannot take responsibility or control the information provided
                        by other users which is made available on the Platform. You may find
                        another user's information to be offensive, harmful, inconsistent,
                        inaccurate, or deceptive. Please use caution and practice safe trading
                        when using the Platform.
                    </div>
                    <br>
                    <div>Please note that there could be risks in dealing with underage persons
                        or people acting under false pretense.
                    </div>
                </div>
                <br>
                <h3>SELLING</h3><br>
                <div> As a registered seller, you are allowed to list item(s) for sale on the
                    Platform in accordance with the Policies which are incorporated by
                    way of reference in this Terms of Use. You must be legally able to sell
                    the item(s) you list for sale on our Platform. You must ensure that the
                    listed items do not infringe upon the intellectual property, trade secret
                    or other proprietary rights or rights of publicity or privacy rights of
                    third parties. Listings may only include text descriptions, graphics and
                    pictures that describe your item for sale. All listed items must be listed
                    in an appropriate category on the Platform. All listed items must be
                    kept in stock for successful fulfilment of sales.
                </div>
                <br>
                <div> The listing description of the item must not be misleading and must
                    describe actual condition of the product. If the item description does
                    not match the actual condition of the item, you agree to refund any
                    amounts that you may have received from the Buyer. You agree not to
                    list a single product in multiple quantities across various categories on
                    the Platform. Petdos reserves the right to delete such multiple listings
                    of the same product listed by you in various categories.
                </div>
                <br>
                <div>That the description of the listing or the listing for the livestock shall
                    be specifically realistic only.
                </div>
                <br>
                <div>The listing for livestock product shall be realistic and shall stand
                    unique to every and one product as there may not be one listing for
                    two products as their realistic description may differ.
                </div>
                <br>
                <div> That it shall be the responsibility of the user / seller to delete, omit,
                    denotify, and delist any listing after sale of the product or otherwise.
                </div>
                <br>
                <h3>PAYMENT</h3><br>
                <div>While availing any of the payment method/s available on the Platform,
                    we will not be responsible or assume any liability, whatsoever in
                    respect of any loss or damage arising directly or indirectly to you due
                    to:<br>
                    <span> Lack of authorization for any transaction/s, or</span><br><br>
                    <span> Exceeding the preset limit mutually agreed by you and between
    "Bank/s", or</span><br><br>
                    <span> Any payment issues arising out of the transaction, or</span><br><br>
                    <span>Decline of transaction for any other reason/s</span><br><br>
                </div>
                <div> All payments made against the purchases/services on Platform by you
                    shall be compulsorily in Indian Rupees acceptable in the Republic of
                    India. Platform will not facilitate transaction with respect to any other
                    form of currency with respect to the purchases made on Platform.
                </div>
                <br>
                <div> Before shipping / delivering your order to you, Seller may request you
                    to provide supporting documents (including but not limited to Govt.
                    issued ID and address proof) to establish the ownership of the
                    payment instrument used by you for your purchase. This is done in the
                    interest of providing a safe online shopping environment to our users.
                </div>
                <br>
                <div>In furtherance; Transactions, Transaction Price and all commercial
                    terms such as Delivery, Dispatch of products and/or services are as per
                    principal to principal bipartite contractual obligations between Buyer
                    and Seller and payment facility is merely used by the Buyer and Seller
                    to facilitate the completion of the Transaction. Use of the payment
                    facility shall not render Petdos liable or responsible for the nondelivery, non-receipt, non-payment, damage,
                    breach of representations
                    and warranties, non-provision of after sales or warranty services or
                    fraud as regards the products and /or services listed on Petdos's
                    Platform.
                </div>
                <br>
                <div> You have specifically authorized Petdos or its service providers to
                    collect, process, facilitate and remit payments and / or the Transaction
                    Price electronically or through Cash on Delivery to and from other
                    users in respect of transactions through Payment Facility. Your
                    relationship with Petdos is on a principal to principal basis and by
                    accepting these Terms of Use you agree that Petdos is an independent
                    contractor for all purposes, and does not have control of or liability for
                    the products or services that are listed on Petdos's Platform that are
                    paid for by using the Payment Facility. Petdos does not guarantee the
                    identity of any user nor does it ensure that a Buyer or a Seller will
                    complete a transaction.
                </div>
                <br>
                <div>You understand, accept and agree that the payment facility provided
                    by Petdos is neither a banking nor financial service but is merely a
                    facilitator providing an electronic, automated online electronic
                    payment, receiving payment through Cash On Delivery, collection and
                    remittance facility for the Transactions on the Petdos Platform using
                    the existing authorized banking infrastructure and Credit Card
                    payment gateway networks. Further, by providing Payment Facility,
                    Petdos is neither acting as trustees nor acting in a fiduciary capacity
                    with respect to the Transaction or the Transaction Price.
                </div>
                <br>
                <h3> PAYMENT FACILITY FOR BUYERS</h3><br>
                <div> You, as a Buyer, understand that upon initiating a Transaction you are
                    entering into a legally binding and enforceable contract with the Seller
                    to purchase the products and /or services from the Seller using the
                    Payment Facility, and you shall pay the Transaction Price through
                    your Issuing Bank to the Seller using Payment Facility.
                </div>
                <br>
                <div>You, as a Buyer, may agree with the Seller through electronic
                    communication and electronic records and using the automated
                    features as may be provided by Payment Facility on any extension /
                    increase in the Dispatch and/or Delivery time and the Transaction
                    shall stand amended to such extent. Any such extension / increase of
                    Dispatch / Delivery time or subsequent novation / variation of the
                    Transaction should be in compliance with Payment Facility Rules and
                    Policies.
                </div>
                <br>
                <div>You, as a Buyer, shall electronically notify Payment Facility using the
                    appropriate Petdos Platform features immediately upon Delivery or
                    non-Delivery within the time period as provided in Policies. Non
                    notification by you of Delivery or non-Delivery within the time period
                    specified in the Policies shall be construed as a deemed Delivery in
                    respect of that Transaction. In case of Cash on Delivery transactions,
                    Buyer is not required to confirm the receipt of products or services.
                </div>
                <br>
                <div>You, as a Buyer, shall be entitled to claim a refund of the Transaction
                    Price (as your sole and exclusive remedy) in case you do not receive
                    the Delivery within the time period agreed in the Transaction or within
                    the time period as provided in the Policies, whichever is earlier. In
                    case you do not raise a refund, claim using Platform features within
                    the stipulated time than this would make you ineligible for a refund.
                </div>
                <br>
                <div> Petdos reserves the exclusive right and its decisions shall be final and
                    binding upon the user in case of any refunds or payments of
                    whatsoever nature.
                </div>
                <br>
                <div>You, as a Buyer, understand that the Payment Facility may not be
                    available in full or in part for certain category of products and/or
                    services and/or Transactions as mentioned in the Policies and hence
                    you may not be entitled to a refund in respect of the Transactions for
                    those products and /or services
                </div>
                <br>
                <div>Except for Cash on Delivery transaction, refund, if any, shall be made
                    at the same Issuing Bank from where Transaction Price was received,
                    or through any other method available on the Platform, as chosen by
                    you.
                </div>
                <br>
                <div> For Cash on Delivery transactions, refunds, if any, will be made via
                    electronic payment transfers.
                </div>
                <br>
                <div> Refund shall be made in Indian Rupees only and shall be equivalent to
                    the Transaction Price received in Indian Rupees.
                </div>
                <br>
                <div>For electronics payments, refund shall be made through payment
                    facility using NEFT / RTGS or any other online banking / electronic
                    funds transfer system approved by Reserve Bank India (RBI).
                </div>
                <br>
                <div> Refunds may be supported for select banks. Where a bank is not
                    supported for processing refunds, you will be required to share
                    alternate bank account details with us for processing the refund.
                </div>
                <br>
                <div>Refund shall be conditional and shall be with recourse available to
                    Petdos in case of any misuse by Buyer.
                </div>
                <br>
                <div> We may also request you for additional documents for verification.</div>
                <br>
                <div>Refund shall be subject to Buyer complying with Policies.</div>
                <br>
                <div>Petdos reserves the right to impose limits on the number of
                    Transactions or Transaction Price which Petdos may receive from on
                    an individual Valid Credit/Debit/ Cash Card / Valid Bank Account/
                    and such other infrastructure or any other financial instrument directly
                    or indirectly through payment aggregator or through any such facility
                    authorized by Reserve Bank of India to provide enabling support
                    facility for collection and remittance of payment or by an individual
                    Buyer during any time period, and reserves the right to refuse to
                    process Transactions exceeding such limit.
                </div>
                <br>
                <div>Petdos reserves the right to refuse to process Transactions by Buyers
                    with a prior history of questionable charges including without
                    limitation breach of any agreements by Buyer with Petdos or
                    breach/violation of any law or any charges imposed by Issuing Bank
                    or breach of any policy.
                </div>
                <br>
                <div>Petdos may do such checks as it deems fit before approving the receipt
                    of/Buyers commitment to pay (for Cash On Delivery transactions)
                    Transaction Price from the Buyer for security or other reasons at the
                    discretion of Petdos. As a result of such check if Petdos is not satisfied
                    with the creditability of the Buyer or genuineness of the Transaction
                    or other reasons at its sole discretion, Petdos shall have the right to
                    reject the receipt of / Buyers commitment to pay Transaction Price.
                    For avoidance of doubt, it is hereby clarified that the ‘Cash on
                    Delivery’ feature for payment, may be disabled for certain account
                    users, at the sole discretion of Petdos.
                </div>
                <br>
                <div>Petdos may delay notifying the payment confirmation i.e. informing
                    Seller to Dispatch, if Petdos deems suspicious or for Buyers
                    conducting high transaction volumes to ensure safety of the
                    Transaction and Transaction Price. In addition, Petdos may hold
                    Transaction Price and Petdos may not inform Seller to Dispatch or
                    remit Transaction Price to law enforcement officials (instead of
                    refunding the same to Buyer) at the request of law enforcement
                    officials or in the event the Buyer is engaged in any form of illegal
                    activity.
                </div>
                <br>
                <div>The Buyer and Seller acknowledge that Petdos will not be liable for
                    any damages, interests or claims etc. resulting from not processing a
                    Transaction/Transaction Price or any delay in processing a
                    Transaction/Transaction Price which is beyond control of Petdos.
                </div>
                <br>
                <h3>COMPLIANCE WITH LAWS</h3><br><br>
                <div>As required by applicable law, if the Customer makes a purchase of an
                    amount equal to or above ₹ 2,00,000.00, the Customer will be required
                    to upload a scanned copy of his/her PAN card on the Platform, within
                    4 days of making the purchase, failing which, the purchase made by
                    the Customer will be cancelled. The requirement to submit the PAN
                    card arises only once and if it has been submitted once by the
                    Customer, it need not be submitted again. The order of the Customer
                    shall stand cancelled if there is a discrepancy between the name of the
                    Customer and the name on the PAN Card.
                </div>
                <br>
                <div>Buyer and Seller shall comply with all the applicable laws (including
                    without limitation Foreign Exchange Management Act, 1999 and the
                    rules made and notifications issued there under and the Exchange
                    Control Manual as may be issued by Reserve Bank of India from time
                    to time, Customs Act, Information and Technology Act, 2000 as
                    amended by the Information Technology (Amendment) Act 2008,
                    Prevention of Money Laundering Act, 2002 and the rules made there
                    under, Foreign Contribution Regulation Act, 1976 and the rules made
                    there under, Income Tax Act, 1961 and the rules made there under,
                    Export Import Policy of government of India) applicable to them
                    respectively for using Payment Facility and Petdos Platform.
                </div>
                <br>
                <h3> BUYER'S ARRANGEMENT WITH ISSUING BANK</h3><br>
                <div>All Valid Credit / Debit/ Cash Card/ and other payment instruments
                    are processed using a Credit Card payment gateway or appropriate
                    payment system infrastructure and the same will also be governed by
                    the terms and conditions agreed to between the Buyer and the
                    respective Issuing Bank and payment instrument issuing company.
                </div>
                <br>
                <div>All Online Bank Transfers from Valid Bank Accounts are processed
                    using the gateway provided by the respective Issuing Bank which
                    support Payment Facility to provide these services to the users. All
                    such Online Bank Transfers on Payment Facility are also governed by
                    the terms and conditions agreed to between Buyer and the respective
                    Issuing Bank.
                </div>
                <br>
                <h3>PETDOS'S REPLACEMENT GUARANTEE*</h3><br>
                <div>Petdos's Replacement Guarantee seeks to assist Buyers who have been
                    defrauded by qualified sellers on the Platform. The return policy
                    period (Petdos's Replacement Guarantee) depends on the product
                    category and the seller. Kindly click here to know the return policy
                    period applicable for different categories. If at the time of delivery
                    and/or within the applicable return policy period, if any defect is
                    found, then the buyer of the product/s can ask for replacement of the
                    product/s from the seller subject to the following terms and conditions.
                </div>
                <br>
                <div> Notify seller of any defects in the product/s at the time of delivery of
                    the product/s and/or within the applicable return policy period and the
                    same product/s will be replaced in return of the defective product/s.
                </div>
                <br>
                <div>Replacement can be for the entire product/s or part/s of the product
                    subject to availability or otherwise of the same with the seller.
                </div>
                <br>
                <span>Following products shall not be eligible for return or replacement: -</span><br>
                <span>Damages due to misuse of product;</span><br><br>
                <span> Incidental damage due to malfunctioning of product;</span><br><br>
                <span>Any consumable item which has been used/installed;</span><br><br>
                <span>Products with tampered or missing serial/UPC numbers;</span><br><br>
                <span> Digital products/services (Flyte music downloads);</span><br><br>
                <span>Any damage/defect which are not covered under the manufacturer's
    warranty;</span><br><br>
                <span> Any product that is returned without all original packaging and
    accessories, including the box, manufacturer's packaging if any, and
    all other items originally included with the product/s delivered;</span><br><br>
                <span>products of whatsoever nature which is 'made to order' on customer's
    request;</span><br><br>
                <span>In case of livestock, the Petdos's Replacement Guarantee policy stands
    at standard 3R Principle which connotes no return, no replacement, no
    refund under any circumstance in any case of whatsoever nature as the
    case maybe and the same is internationally accredited principle of
    good practice under all regimes of law globally – subject to the
    conditions as under: -</span><br><br>
                <div> In order to safeguard the interest of the users, the livestock
                    products shall be delivered at Petdos endorsed or verified veterinarian
                    or at the veterinarian of the buyers choice or at any other address
                    provided by the buyer as the case may be, so that all and every detail
                    of whatsoever nature can be verified, looked into with utmost fitness
                    of the matter; this methodology or standard of delivery is being
                    instrumented with the object and reasoning to intent that no user may
                    disclaim and a’caveat standard 3R principle.
                </div>
                <br>
                <div>The above optional delivery maybe subject to certain conditions
                    where the livestock product airlifted or is being delivered after
                    through checks as per normal good standard market practice.
                </div>
                <br>
                <div> On products of whatsoever nature, qualified sellers accept 3-day
                    exchange subject to the following conditions:
                </div>
                <br>
                <div> Returns of products of whatsoever nature shall only be made if the
                    products are not used (other than for trial), altered, washed, soiled or
                    damaged in any way.
                </div>
                <br>
                <div>Original tags and packaging should be intact. For items that come in
                    branded packaging, the box should be undamaged.
                </div>
                <br>
                <div>Returns are not applicable for 'Made to order' products of whatsoever
                    nature.
                </div>
                <br>
                <div>Damaged or defective or 'Not as described' products in Lifestyle
                    category (includes clothing, footwear, etc.) are meanwhile covered by
                    the 3-Day Replacement Guarantee. Kindly click here to know the
                    return policy period (Replacement Guarantee) applicable for different
                    categories.
                </div>
                <br>
                <div> If Petdos has any suspicion or knowledge that any of its buyers and
                    sellers are involved in any activity that is intended to provide claims
                    or information that is false or not genuine, Petdos may also, while
                    reserving its rights to initiate civil and/or criminal proceedings against
                    such member buyers and sellers, at its sole discretion, suspend, block,
                    restrict, cancel the Display Name of such buyers and sellers and/or
                    disqualify that user and any related users from availing protection
                    through this program. Customers who have been blocked for any
                    suspicious or fraudulent activity on Petdos will not be allowed to
                    return their products.
                </div>
                <br>
                <div> Petdos reserves its right to initiate civil and/or criminal proceedings
                    against a user who, files an invalid and/or false claims or provides
                    false, incomplete, or misleading information. In addition to the legal
                    proceedings as aforesaid, Petdos may at its sole discretion suspend,
                    block, restrict, cancel the Display Name [and its related Display
                    Names] of such user and/or disqualify that user and any related users
                    from availing protection through this program. Any person who,
                    knowingly and with intent to injure, defraud or deceive, files a
                    Fraudulent Complaint containing false, incomplete, or misleading
                    information may be guilty of a criminal offence and will be prosecuted
                    to the fullest extent of the law.
                </div>
                <br>
                <div> Petdos reserves the right to make final decision qua any return as the
                    case may me and the same shall be final and binding on the user.
                </div>
                <br>
                <h3>EXCHANGE OFFERS</h3><br>
                <div> By participating in the exchange, I confirm that I am the sole and
                    absolute owner and/or user of the product mentioned above (device).
                </div>
                <br>
                <div>I confirm that device which I am exchanging under the buyback
                    program is genuine and is not counterfeit, free from any and all
                    encumbrances, liens, attachments, disputes, legal flaws, exchange or
                    any Agreement of Sale etc. and I have got the clear ownership of the
                    said device.
                </div>
                <br>
                <div>You agree to indemnity and keep indemnifying www.thepetnest.com
                    and any future buyer of the device against all or any third party
                    claims, demand, cost, expenses including attorney fees which may be
                    suffered, incurred, undergone and / or sustained by
                    www.thepetnest.com, its affiliates or any future buyer due to usage
                    of the device by you till date and you undertake to make good the
                    same.
                </div>
                <br>
                <h3>LIMITATION OF LIABILITY</h3><br>
                <div>Petdos we do not warrant that Product description or other content of
                    this Platform is accurate, complete, reliable, current, or error-free and
                    assumes no liability in this regard.
                </div>
                <br>
                <div>It also put to disclaimer / caveat / intimation / notice that all legal - requirements, sanctions,
                    restrictions, licenses, authorizations,
                    authorities, attornments, representations, notifications, classifications,
                    mandates of law including and excluding the law for the time being in
                    force or otherwise; or otherwise ejusdem genris qua the user shall be
                    his / her own, sole and personal responsibility and that neither the
                    platform nor Petdos Online Private Limited shall be responsible in any
                    manner under any circumstance or whatsoever nature for any liability
                    whether civil, criminal, vicarious, personal, professional and
                    commercial under mandates of law including and excluding the law
                    for the time being in force or otherwise; or otherwise.
                </div>
                <div>In no event shall Petdos be liable for any special, incidental, indirect
                    or consequential damages of any kind in connection with these terms
                    of use, even if user has been informed or not in advance of the
                    possibility of such damages. THE PLATFORM SHALL HAVE NO
                    LIABILITY TO ANY USER OF ANY KIND WHATSOEVER IN
                    CASE OF ANY DISPUTE OF WHATSOEVER NATURE IN ANY
                    MANNER FOR ANY OR EVERY SALE / PURCHASE OF GOODS
                    AND / OR SERVICES.
                </div>
                <br>
                <div><b>Pedigree - </b>You shall be responsible for acquiring the pedigree
                    description of the breed before placing an order, Petdos has no hand in
                    between the pedigree description of the breed between the parties.
                    Any complaints suffering from congenital / genetic disease, habitants
                    qua pedigree is not liable to the seller or to the platform. Pedigree
                    description is only presented before Sale and not after Sale, that too if
                    records are available. It is the sole responsibility of the user to check
                    the pedigree before sale, if in any case the pedigree description is not
                    available as per records; Petdos is not solemnly responsible for the
                    undoing, as description availability is as per past and document
                    records. Petdos is not responsible for any return or refund made after
                    the purchase of the product, if the reason of refund or return is
                    pedigree description in any case. The Doctrine of Caveat emptor
                    implies on all the users engaged on the platform of Petdos, while
                    purchasing a product.
                </div>
                <br>
                <div><b>Breeds Certificate -</b> All the users active on the Petdos platform, while
                    placing an order should be aware of the fact that breed’s certificate is
                    presented on demand to the buyer and Petdos does not provide any
                    such information as a complimentary fact. Petdos is not liable to any
                    of its user to provide any such information in any way or in relation to
                    the buyer, as the breed’s certificate is provided as per the availability
                    of records. The user cannot hold on Petdos for any claim under the
                    breed’s certificate, as Petdos has no direct link with the certification of
                    purity of the breed. No refund or return policy can be claimed under
                    this clause, as Petdos hold no such implied or expressed character.
                </div>
                <br>
                <div><b>Delivery Clause -</b>
                    <div>At the point of delivery, if the Buyer denies the
                        delivery 0% Refund will be initiated & if denial of service by Petdos
                        then 50% refund. At the time of delivery or after delivery, if the buyer
                        asks for any kind of refund due to whatsoever reason, Petdos is not
                        liable is refund back any deposits made to Petdos by the buyer. After
                        delivery, due to whatsoever reason the amount will not be refunded
                        back to the buyer. Once the product is delivered, there will be no such
                        Verification being held by Petdos; medical reports, diet chat & other
                        necessary documents related to the Pet will be provided to the buyer
                        by Petdos. Use is free at his own cost for such verification at the time
                        of delivery. All other future claims are barred or waive if no
                        verification at delivery. Livestock products are Non-refundable &
                        Non- exchangeable, hence once product ordered & received by the
                        buyer cannot be returned back to Petdos under any circumstances.
                        Upon travel the delivery includes the approximate cost in itself, no
                        extra charges are calculated. In case of livestock, the Petdos's delivery
                        policy stands at standard 3R Principle which connotes no return, no
                        replacement, no refund under any circumstance in any case of
                        whatsoever nature as the case may be and the same is internationally
                        accredited principle of good practice under all regimes of law globally – subject to the conditions as under.
                        In order to safeguard the interest
                        of the users, the livestock products shall be delivered at Petdos
                        endorsed or verified veterinarian or at the veterinarian of the buyers
                        choice or at any other address provided by the buyer as the case may
                        be, so that all and every detail of whatsoever nature can be verified,
                        looked into with utmost fitness of the matter; this methodology or
                        standard of delivery is being instrumented with the object and
                        reasoning to intent that no user may disclaim and a’caveat standard 3R
                        principle. The above optional delivery maybe subject to certain
                        conditions where the livestock product airlifted or is being delivered
                        after through checks as per normal good standard market practice.
                    </div>
                    <br>
                    <div><b>Description -</b> We ‘Petdos’ on your platform announce and proclaim
                        that all the content available on the platform for the users is organic
                        and not filtered. The Pet’s description provided by Petdos is in its
                        original and final form only, as we do not believe in any sort of
                        filtration in any photo or content or any description provided by us.
                        Any queries or any sort of issues arising after the delivery of the
                        product, in reference to the pet’s description will not be entertained by
                        Petdos, which may lead to return or refund of the product, as there will
                        be no such refund or return initiated by Petdos after final delivery.
                    </div>
                    <br>
                    <div><b>Advertisement -</b> Petdos does not wish to engage any third party for
                        any sort off advertisement on its platform, for prompting any products
                        and other relevant stuff regarding the same.
                    </div>
                    <br>
                    <div><b>Jurisdiction - </b>Any legal dispute or otherwise qua the platform with
                        Petdos shall only be subject to the territorial jurisdiction of the courts
                        at South Delhi District.
                    </div>
                    <br>
                    <h3>CONTACT US</h3><br>
                    <div> Please contact us for any questions or comments (including all
                        inquiries unrelated to copyright infringement) regarding this Platform.
                    </div>
                    <br>
                    <h3>Particulars for contact: -</h3><br>
                    <span><b>Email:</b> <a herf="mailto:vc@thepetnest.com"><span class="_cf_email_" data-cfemail="512732112539342134253f3422257f323e3c">[email&#160;protected]</span></a></span><br><br>
                    <span><b>Phone:</b> +91 931 976 4169</span><br><br>
                    <span><b>Time:</b> Mon - Sat (9:00 - 18:00)</span><br>
                    <h3>GRIEVANCE OFFICER</h3><br>
                    <div> In accordance with Information Technology Act 2000 and rules made
                        there under, the name and contact details of the Grievance Officer are
                        provided below:<br><br>
                        <b>ThePetNest Grievance Officer
                            <div><br>
                                <b>M/s. Petdos Online Pvt Ltd</b><br><br>
                                <b>55, 2nd Floor, Lane 2, Westend Marg, Saidullajab, Near Saket Metro Station, New Delhi, Delhi,
                                    110030</b><br><br>
                                <b><b>NO WAIVER IMPLIED - </b>Any failure on part of Petdos to enforce at
                                    any time any of the provisions of these of Agreement, or the failure to
                                    require at any time performance by you of any of the provisions of
                                    these provisions, shall in no way be construed to be a present or future
                                    waiver of such provisions, nor in any way affect our right to enforce
                                    each and every such provision thereafter. The express waiver by us of
                                    any provision, condition or requirement of these provisions shall not
                                    constitute a waiver of any future obligation to comply with such
                                    provision, condition or requirement.</b><br><br>
                                <b>If you come across any abuse or violation of the Policy, please report to <a href="/cdn-cgi/l/email-protection" class="_cf_email_" data-cfemail="1c6a7f5c6874796c796872796f68327f7371">[email&#160;protected]</a></b>
                            </div>
                        </b>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>